/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BonInABoxScriptService);
  }
}(this, function(expect, BonInABoxScriptService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BonInABoxScriptService.GetServerStatus200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetServerStatus200Response', function() {
    it('should create an instance of GetServerStatus200Response', function() {
      // uncomment below and update the code to test GetServerStatus200Response
      //var instance = new BonInABoxScriptService.GetServerStatus200Response();
      //expect(instance).to.be.a(BonInABoxScriptService.GetServerStatus200Response);
    });

    it('should have the property runsEnabled (base name: "runsEnabled")', function() {
      // uncomment below and update the code to test the property runsEnabled
      //var instance = new BonInABoxScriptService.GetServerStatus200Response();
      //expect(instance).to.be();
    });

    it('should have the property savePipelineToServer (base name: "savePipelineToServer")', function() {
      // uncomment below and update the code to test the property savePipelineToServer
      //var instance = new BonInABoxScriptService.GetServerStatus200Response();
      //expect(instance).to.be();
    });

    it('should have the property condaPackEnabled (base name: "condaPackEnabled")', function() {
      // uncomment below and update the code to test the property condaPackEnabled
      //var instance = new BonInABoxScriptService.GetServerStatus200Response();
      //expect(instance).to.be();
    });

    it('should have the property myFilesEnabled (base name: "myFilesEnabled")', function() {
      // uncomment below and update the code to test the property myFilesEnabled
      //var instance = new BonInABoxScriptService.GetServerStatus200Response();
      //expect(instance).to.be();
    });

    it('should have the property antivirusEnabled (base name: "antivirusEnabled")', function() {
      // uncomment below and update the code to test the property antivirusEnabled
      //var instance = new BonInABoxScriptService.GetServerStatus200Response();
      //expect(instance).to.be();
    });

    it('should have the property antivirusReachable (base name: "antivirusReachable")', function() {
      // uncomment below and update the code to test the property antivirusReachable
      //var instance = new BonInABoxScriptService.GetServerStatus200Response();
      //expect(instance).to.be();
    });

  });

}));
