metadata:
  type: dict
  required: true
  schema:
    name:
      type: string
      required: true

    description:
      required: true
      type: string

    lifecycle:
      required: true
      type: dict
      oneof_schema:
        - status:
            type: string
            allowed: ["in_development", "in_review", "reviewed"]
            required: true
          message:
            type: string
            required: false
        - status:
            type: string
            allowed: ["deprecated"]
            required: true
          message:
            type: sting
            required: true

    author:
      type: list
      required: true
      schema:
        type: dict
        schema:
          name:
            type: string
            required: true
          email:
            type: string
            required: false
          identifier:
            type: string
            required: false

    reviewer:
      type: list
      schema:
        type: dict
        schema:
          name:
            type: string
            required: true
          email:
            type: string
            required: false
          identifier:
            type: string
            required: false

    license:
      type: string
      required: false

    external_link:
      required: false
      nullable: true
      type: string
      regex: '^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$'

    references:
      required: false
      nullable: true
      type: list
      schema:
        type: dict
        schema:
          text:
            required: true
            type: string
          doi:
            required: false
            type: string

inputs:
  required: false
  nullable: true
  type: dict
  keysrules:
   type: string
  valuesrules:
    schema:
      label:
        required: true
        type: string
      description:
        required: true
        type: string
      type:
        required: true
        type: string
        oneof:
        - forbidden: [options, "options[]", object, "object[]"]
        - allowed: [options, "options[]"]
          dependencies: options
        - allowed: [object, "object[]"]
          dependencies: properties
      options:
        required: false
        type: list
        dependencies:
          type: [options, "options[]"]
      properties:
        required: false
        type: list
        dependencies:
          type: [object, "object[]"]

      weight:
        required: false
        type: number

      example:
        required: false
        nullable: true
        oneof:
        - type: number
        - type: string
          nullable: true
        - type: boolean
        - type: list
        - type: dict
          dependencies:
            type: [object]

outputs:
  required: true
  nullable: false
  type: dict
  keysrules:
   type: string
   forbidden: [info, warning, error]
  valuesrules:
    schema:
      label:
        required: true
        type: string
      description:
        required: true
        type: string
      type:
        required: true
        type: string
        oneof:
        - forbidden: [options, "options[]", object, "object[]"]
        - allowed: [options, "options[]"]
          dependencies: options
        - allowed: [object, "object[]"]
          dependencies: properties
      options:
        required: false
        type: list
        dependencies:
          type: [options, "options[]"]
      properties:
        required: false
        type: list
        dependencies:
          type: [object, "object[]"]
      range:
        required: false
        type: list
        dependencies:
          type:
            - image/tiff;application=geotiff
            - image/tiff;application=geotiff[]

      weight:
        required: false
        type: number

      example:
        required: false
        nullable: true
        oneof:
        - type: number
        - type: string
          nullable: true
        - type: boolean
        - type: list
        - type: dict
          dependencies:
            type: [object]

edges:
  required: true

nodes:
  required: true
