project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!ui/"

website:
  title: "BON in a Box"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: About
      - how_to_install.qmd
      - how_to_use.qmd
      - text: "Contribute a pipeline"
        menu: 
          - href: what_to_contribute.qmd
            text: "Should you contribute?"
          - href: how_to_contribute.qmd
            text: "Contribution instructions"
          - href: pipeline_standards.qmd
            text: "Pipeline standards"
      - peer_review.qmd
  sidebar:
    style: "floating"
    search: true
    logo: Biab_large.png

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

