project:
  type: website
  output-dir: docs

website:
  title: "bon-in-a-box-pipeline-engine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - how_to_install.qmd
      - developer_documentation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

