project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!ui/"
    - "!README-dev.md"

website:
  title: "BON in a Box"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: About
      - how_to_install.qmd
      - how_to_contribute.qmd
      - working_with_stac.qmd
  sidebar:
    style: "floating"
    search: true
    logo: Biab_large.png

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

