# Development compose file.
# Contains configurations specific to the development environment.
name: bon-in-a-box_dev

services:
  ## UI server to use when developing UI code
  ui:
    container_name: biab-ui
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    user: "node"
    volumes:
      - "./ui:/app:rw"
    working_dir: "/app"
    command: sh -c "cd BonInABoxScriptService; npm run build; cd -; npm install; npm start;"
    expose:
      - "3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      # https://github.com/facebook/create-react-app/issues/11779
      WDS_SOCKET_PORT: 0
    depends_on:
      - script-server
      - python-api

  viewer:
    container_name: biab-viewer
    image: node:current-alpine3.18
    volumes:
      - "./viewer:/app:rw"
    working_dir: "/app"
    command: sh -c "npm install; npm run dev;"
    expose:
      - "80"

  ## In the DEV version, using a volume and a single docker. To rebuild without restarting everything, use
  ## docker exec -it biab-script-server sh -c "cd /home/gradle/project/ && gradle build"
  script-server:
    build:
      context: ./script-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./script-server:/home/gradle/project:rw
    working_dir: /home/gradle/project
    command: gradle run
    environment:
      DEV: true

  python-api:
    build:
      context: python-api/
      args:
        BIAB_VERSION: "dev"

  gateway:
    image: nginxinc/nginx-unprivileged
    depends_on:
      - ui
      - viewer
      - openapi_swagger

  ## Server to use when making changes to the OpenAPI specification.
  openapi_swagger:
    container_name: swagger_ui
    image: swaggerapi/swagger-ui:v5.17.14
    volumes:
      - ./script-server/api/openapi.yaml:/openapi.yaml:ro
    expose:
      - "8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
      BASE_URL: /swagger
