# Production compose file.
# Contains configurations specific to the production environment.

services:
  ui:
    container_name: biab-ui
    image: geobon/bon-in-a-box:ui
    # build:
    #   context: ./ui
    #   dockerfile: Dockerfile.prod
    expose:
      - "80"

  viewer:
    #image: geobon/bon-in-a-box:viewer
    #build:
    #  context: ./viewer
    #  dockerfile: Dockerfile.prod
    #expose:
    #  - "80"

  script-server:
    image: geobon/bon-in-a-box:script-server
    # build:
    #   context: ./script-server/
    #   dockerfile: Dockerfile.prod
