# Production compose file.
# Contains configurations specific to the production environment.
name: bon-in-a-box

services:

  script-server:
    image: ghcr.io/geo-bon/bon-in-a-box-pipeline-engine/script-server:${DOCKER_SUFFIX}
    # build:
    #   context: ./script-server/
    #   dockerfile: Dockerfile.prod

  gateway:
    image: ghcr.io/geo-bon/bon-in-a-box-pipeline-engine/gateway:${DOCKER_SUFFIX}
    # build:
    #   context: .
    #   dockerfile: Dockerfile.gateway.prod
    expose:
      - "80"
