# Production compose file.
# Contains configurations specific to the production environment.

services:

  script-server:
    image: geobon/bon-in-a-box:script-server${DOCKER_SUFFIX}
    # build:
    #   context: ./script-server/
    #   dockerfile: Dockerfile.prod

  gateway:
    image: geobon/bon-in-a-box:gateway${DOCKER_SUFFIX}
    # build:
    #   context: .
    #   dockerfile: Dockerfile.gateway.prod
    expose:
      - "80"

volumes:
  conda-dir:
    name: "conda-dir"
  conda-cache:
    name: "conda-cache"
  conda-env-yml:
    name: "conda-env-yml"
  r-libs-user:
    name: "r-libs-user"