---
title: "Peer review"
format: html
---

## **Peer review process**

Each pipeline will be reviewed by 2-5 people for scientific rigor, usability, and generalizability. The contributor will suggest potential reviewers, and they will be contacted by the BON in a Box team. Additional reviewers will be chosen by the BON in a Box team. It is encouraged to have reviewers from both the academic and policy sphere (e.g. a government scientist). The contributor will specify whether the pipeline is a pipeline for reporting, a pipeline for BONs, or a sampling prioritization pipeline.

The pipelines will be reviewed based on the following criteria:

-   **Scientific rigor:** are the models scientifically robust and accurate? Is it supported by peer reviewed literature?

-   **Generalizability:** does the pipeline work for different regions, species, scales, etc.? If not, are these limitations communicated clearly?

-   **Code readability:** Is the code easy to read, understandable, and well documented?

-   **Modularity:** Is the code divided into logical, modular steps where each script performs one task?

-   **Data use:** Does the pipeline support both user data and publicly available data? Is this data loaded with an API or will it require updating? Are users able to easily access this data?

-   **Functionality:** Does the pipeline run? Or are there bugs? 

-   **Documentation:** Is there metadata for both the individual scripts and the pipeline? Is there a markdown tutorial?

-   **Usability:** Is the pipeline easy to use and understand for a non expert? Is there adequate guidance on how to parameterize it?

The reviewers will test the pipeline with a number of data sets, species, and scales based on their expertise, and provide feedback. The reviewer will decide if the pipeline should be accepted with minor revisions, needs to be revised and resubmitted, or is not suitable for BON in a Box.

### **When is a pipeline ready for peer review?**

Pipelines are ready for peer review when:

-   The pipeline meets all of the [quality requirements](pipelines_standards.qmd)

-   The pipeline runs without errors with the defaults, and with different inputs and outputs, including publicly available data or user data

-   The pipeline has been tested with different parameters (geographical areas, ecosystems, scales, and species) and the results make sense

## **Pipeline publication**

When pipelines have been peer reviewed and are accepted, they will be published on [Zenodo](https://zenodo.org/) and given a DOI, which will be cited whenever the pipeline is used.

## Instructions for reviewers

Reviewers will evaluate the code, method implementation, and usability of the pipeline. Reviewers will provide comments in the pipeline review form. Reviewers can also comment directly in the pull request on GitHub.

#### Download peer review form here (ADD FILE)
