
FROM node:current-alpine3.18 as builder

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# Workaround with [] for file that is not always there : https://stackoverflow.com/a/46801962/3519951
COPY package.json package-lock.jso[n] ./

# add app
COPY . ./
RUN npm install && npm run build