/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateItem200Response from '../model/CreateItem200Response';
import CreateItemRequest from '../model/CreateItemRequest';
import DeleteItem200Response from '../model/DeleteItem200Response';
import DeleteItemRequest from '../model/DeleteItemRequest';
import GetFileStorage200Response from '../model/GetFileStorage200Response';
import GetRootItems200ResponseInner from '../model/GetRootItems200ResponseInner';
import GetRootItems403Response from '../model/GetRootItems403Response';
import IsFileManagerDisabled200Response from '../model/IsFileManagerDisabled200Response';
import MoveCopyItem200Response from '../model/MoveCopyItem200Response';
import MoveCopyItemRequest from '../model/MoveCopyItemRequest';
import RenameItem200Response from '../model/RenameItem200Response';
import RenameItemRequest from '../model/RenameItemRequest';
import UploadFile200Response from '../model/UploadFile200Response';

/**
* FileManager service.
* @module api/FileManagerApi
* @version 1.0.0
*/
export default class FileManagerApi {

    /**
    * Constructs a new FileManagerApi. 
    * @alias module:api/FileManagerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createItem operation.
     * @callback module:api/FileManagerApi~createItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateItem200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a file or folder.
     * @param {String} id The parent folder path where the new item will be created.
     * @param {module:model/CreateItemRequest} createItemRequest 
     * @param {module:api/FileManagerApi~createItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateItem200Response}
     */
    createItem(id, createItemRequest, callback) {
      let postBody = createItemRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling createItem");
      }
      // verify the required parameter 'createItemRequest' is set
      if (createItemRequest === undefined || createItemRequest === null) {
        throw new Error("Missing the required parameter 'createItemRequest' when calling createItem");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateItem200Response;
      return this.apiClient.callApi(
        '/fm-api/files/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteItem operation.
     * @callback module:api/FileManagerApi~deleteItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteItem200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a file or folder.
     * @param {module:model/DeleteItemRequest} deleteItemRequest 
     * @param {module:api/FileManagerApi~deleteItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteItem200Response}
     */
    deleteItem(deleteItemRequest, callback) {
      let postBody = deleteItemRequest;
      // verify the required parameter 'deleteItemRequest' is set
      if (deleteItemRequest === undefined || deleteItemRequest === null) {
        throw new Error("Missing the required parameter 'deleteItemRequest' when calling deleteItem");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = DeleteItem200Response;
      return this.apiClient.callApi(
        '/fm-api/files', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllItems operation.
     * @callback module:api/FileManagerApi~getAllItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GetRootItems200ResponseInner>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the list of all files and folders uploaded by the user.
     * @param {module:api/FileManagerApi~getAllItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/GetRootItems200ResponseInner>}
     */
    getAllItems(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [GetRootItems200ResponseInner];
      return this.apiClient.callApi(
        '/fm-api/files/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFileStorage operation.
     * @callback module:api/FileManagerApi~getFileStorageCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetFileStorage200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets the total, used, and free storage.
     * @param {module:api/FileManagerApi~getFileStorageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetFileStorage200Response}
     */
    getFileStorage(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetFileStorage200Response;
      return this.apiClient.callApi(
        '/fm-api/info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRootItems operation.
     * @callback module:api/FileManagerApi~getRootItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GetRootItems200ResponseInner>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the list of root files and folders uploaded by the user.
     * @param {module:api/FileManagerApi~getRootItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/GetRootItems200ResponseInner>}
     */
    getRootItems(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [GetRootItems200ResponseInner];
      return this.apiClient.callApi(
        '/fm-api/files', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubfolderItems operation.
     * @callback module:api/FileManagerApi~getSubfolderItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the list of files and folders uploaded by the user under a specific subfolder.
     * @param {String} id The path of the parent folder contaning the files we want to get.
     * @param {module:api/FileManagerApi~getSubfolderItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    getSubfolderItems(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getSubfolderItems");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Object];
      return this.apiClient.callApi(
        '/fm-api/files/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the isFileManagerDisabled operation.
     * @callback module:api/FileManagerApi~isFileManagerDisabledCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IsFileManagerDisabled200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns whether the file manager is disabled or not.
     * @param {module:api/FileManagerApi~isFileManagerDisabledCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IsFileManagerDisabled200Response}
     */
    isFileManagerDisabled(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = IsFileManagerDisabled200Response;
      return this.apiClient.callApi(
        '/fm-api/is_disabled', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the moveCopyItem operation.
     * @callback module:api/FileManagerApi~moveCopyItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MoveCopyItem200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Moves or copies one or multiple files/folders.
     * @param {module:model/MoveCopyItemRequest} moveCopyItemRequest 
     * @param {module:api/FileManagerApi~moveCopyItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MoveCopyItem200Response}
     */
    moveCopyItem(moveCopyItemRequest, callback) {
      let postBody = moveCopyItemRequest;
      // verify the required parameter 'moveCopyItemRequest' is set
      if (moveCopyItemRequest === undefined || moveCopyItemRequest === null) {
        throw new Error("Missing the required parameter 'moveCopyItemRequest' when calling moveCopyItem");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = MoveCopyItem200Response;
      return this.apiClient.callApi(
        '/fm-api/files', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the renameItem operation.
     * @callback module:api/FileManagerApi~renameItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RenameItem200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Renames a file or folder.
     * @param {String} id The current path/id of the file or folder that is being renamed.
     * @param {module:model/RenameItemRequest} renameItemRequest 
     * @param {module:api/FileManagerApi~renameItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RenameItem200Response}
     */
    renameItem(id, renameItemRequest, callback) {
      let postBody = renameItemRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling renameItem");
      }
      // verify the required parameter 'renameItemRequest' is set
      if (renameItemRequest === undefined || renameItemRequest === null) {
        throw new Error("Missing the required parameter 'renameItemRequest' when calling renameItem");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RenameItem200Response;
      return this.apiClient.callApi(
        '/fm-api/files/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the uploadFile operation.
     * @callback module:api/FileManagerApi~uploadFileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UploadFile200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Uploads a file to the user's profile.
     * @param {String} id The parent folder path where the new item will be uploaded.
     * @param {File} file The file that will be uploaded
     * @param {module:api/FileManagerApi~uploadFileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UploadFile200Response}
     */
    uploadFile(id, file, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling uploadFile");
      }
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling uploadFile");
      }

      let pathParams = {
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = UploadFile200Response;
      return this.apiClient.callApi(
        '/fm-api/upload', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
