/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateItem200ResponseResult model module.
 * @module model/CreateItem200ResponseResult
 * @version 1.0.0
 */
class CreateItem200ResponseResult {
    /**
     * Constructs a new <code>CreateItem200ResponseResult</code>.
     * @alias module:model/CreateItem200ResponseResult
     * @param id {String} 
     * @param name {String} 
     * @param type {module:model/CreateItem200ResponseResult.TypeEnum} 
     */
    constructor(id, name, type) { 
        
        CreateItem200ResponseResult.initialize(this, id, name, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, type) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>CreateItem200ResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateItem200ResponseResult} obj Optional instance to populate.
     * @return {module:model/CreateItem200ResponseResult} The populated <code>CreateItem200ResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateItem200ResponseResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateItem200ResponseResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateItem200ResponseResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateItem200ResponseResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

CreateItem200ResponseResult.RequiredProperties = ["id", "name", "type"];

/**
 * @member {String} id
 */
CreateItem200ResponseResult.prototype['id'] = undefined;

/**
 * @member {String} name
 */
CreateItem200ResponseResult.prototype['name'] = undefined;

/**
 * @member {module:model/CreateItem200ResponseResult.TypeEnum} type
 */
CreateItem200ResponseResult.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CreateItem200ResponseResult['TypeEnum'] = {

    /**
     * value: "file"
     * @const
     */
    "file": "file",

    /**
     * value: "folder"
     * @const
     */
    "folder": "folder"
};



export default CreateItem200ResponseResult;

