/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetFileStorage200ResponseStats model module.
 * @module model/GetFileStorage200ResponseStats
 * @version 1.0.0
 */
class GetFileStorage200ResponseStats {
    /**
     * Constructs a new <code>GetFileStorage200ResponseStats</code>.
     * @alias module:model/GetFileStorage200ResponseStats
     * @param total {Number} 
     * @param used {Number} 
     * @param free {Number} 
     */
    constructor(total, used, free) { 
        
        GetFileStorage200ResponseStats.initialize(this, total, used, free);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, used, free) { 
        obj['total'] = total;
        obj['used'] = used;
        obj['free'] = free;
    }

    /**
     * Constructs a <code>GetFileStorage200ResponseStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFileStorage200ResponseStats} obj Optional instance to populate.
     * @return {module:model/GetFileStorage200ResponseStats} The populated <code>GetFileStorage200ResponseStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFileStorage200ResponseStats();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('used')) {
                obj['used'] = ApiClient.convertToType(data['used'], 'Number');
            }
            if (data.hasOwnProperty('free')) {
                obj['free'] = ApiClient.convertToType(data['free'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetFileStorage200ResponseStats</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetFileStorage200ResponseStats</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetFileStorage200ResponseStats.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

GetFileStorage200ResponseStats.RequiredProperties = ["total", "used", "free"];

/**
 * @member {Number} total
 */
GetFileStorage200ResponseStats.prototype['total'] = undefined;

/**
 * @member {Number} used
 */
GetFileStorage200ResponseStats.prototype['used'] = undefined;

/**
 * @member {Number} free
 */
GetFileStorage200ResponseStats.prototype['free'] = undefined;






export default GetFileStorage200ResponseStats;

