/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetFileStorage200ResponseStats from './GetFileStorage200ResponseStats';

/**
 * The GetFileStorage200Response model module.
 * @module model/GetFileStorage200Response
 * @version 1.0.0
 */
class GetFileStorage200Response {
    /**
     * Constructs a new <code>GetFileStorage200Response</code>.
     * @alias module:model/GetFileStorage200Response
     * @param stats {module:model/GetFileStorage200ResponseStats} 
     */
    constructor(stats) { 
        
        GetFileStorage200Response.initialize(this, stats);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, stats) { 
        obj['stats'] = stats;
    }

    /**
     * Constructs a <code>GetFileStorage200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFileStorage200Response} obj Optional instance to populate.
     * @return {module:model/GetFileStorage200Response} The populated <code>GetFileStorage200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFileStorage200Response();

            if (data.hasOwnProperty('stats')) {
                obj['stats'] = GetFileStorage200ResponseStats.constructFromObject(data['stats']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetFileStorage200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetFileStorage200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetFileStorage200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `stats`
        if (data['stats']) { // data not null
          GetFileStorage200ResponseStats.validateJSON(data['stats']);
        }

        return true;
    }


}

GetFileStorage200Response.RequiredProperties = ["stats"];

/**
 * @member {module:model/GetFileStorage200ResponseStats} stats
 */
GetFileStorage200Response.prototype['stats'] = undefined;






export default GetFileStorage200Response;

