/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetHPCStatus200ResponseValue model module.
 * @module model/GetHPCStatus200ResponseValue
 * @version 1.0.0
 */
class GetHPCStatus200ResponseValue {
    /**
     * Constructs a new <code>GetHPCStatus200ResponseValue</code>.
     * @alias module:model/GetHPCStatus200ResponseValue
     * @extends Object
     */
    constructor() {

        GetHPCStatus200ResponseValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {
    }

    /**
     * Constructs a <code>GetHPCStatus200ResponseValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetHPCStatus200ResponseValue} obj Optional instance to populate.
     * @return {module:model/GetHPCStatus200ResponseValue} The populated <code>GetHPCStatus200ResponseValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetHPCStatus200ResponseValue();

            ApiClient.constructFromObject(data, obj, 'String');


            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetHPCStatus200ResponseValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetHPCStatus200ResponseValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {module:model/GetHPCStatus200ResponseValue.StateEnum} state
 */
GetHPCStatus200ResponseValue.prototype['state'] = undefined;

/**
 * @member {String} image
 */
GetHPCStatus200ResponseValue.prototype['image'] = undefined;

/**
 * @member {String} message
 */
GetHPCStatus200ResponseValue.prototype['message'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
GetHPCStatus200ResponseValue['StateEnum'] = {

    /**
     * value: "NOT_CONFIGURED"
     * @const
     */
    "NOT_CONFIGURED": "NOT_CONFIGURED",

    /**
     * value: "CONFIGURED"
     * @const
     */
    "CONFIGURED": "CONFIGURED",

    /**
     * value: "PREPARING"
     * @const
     */
    "PREPARING": "PREPARING",

    /**
     * value: "READY"
     * @const
     */
    "READY": "READY",

    /**
     * value: "ERROR"
     * @const
     */
    "ERROR": "ERROR"
};



export default GetHPCStatus200ResponseValue;

