/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetRootItems200ResponseInner model module.
 * @module model/GetRootItems200ResponseInner
 * @version 1.0.0
 */
class GetRootItems200ResponseInner {
    /**
     * Constructs a new <code>GetRootItems200ResponseInner</code>.
     * @alias module:model/GetRootItems200ResponseInner
     * @param id {String} 
     * @param value {String} 
     * @param type {String} 
     * @param size {Number} 
     */
    constructor(id, value, type, size) { 
        
        GetRootItems200ResponseInner.initialize(this, id, value, type, size);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, value, type, size) { 
        obj['id'] = id;
        obj['value'] = value;
        obj['type'] = type;
        obj['size'] = size;
    }

    /**
     * Constructs a <code>GetRootItems200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRootItems200ResponseInner} obj Optional instance to populate.
     * @return {module:model/GetRootItems200ResponseInner} The populated <code>GetRootItems200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRootItems200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetRootItems200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetRootItems200ResponseInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetRootItems200ResponseInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

GetRootItems200ResponseInner.RequiredProperties = ["id", "value", "type", "size"];

/**
 * @member {String} id
 */
GetRootItems200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} value
 */
GetRootItems200ResponseInner.prototype['value'] = undefined;

/**
 * @member {String} type
 */
GetRootItems200ResponseInner.prototype['type'] = undefined;

/**
 * @member {Number} size
 */
GetRootItems200ResponseInner.prototype['size'] = undefined;






export default GetRootItems200ResponseInner;

