/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetServerStatus200Response model module.
 * @module model/GetServerStatus200Response
 * @version 1.3.1
 */
class GetServerStatus200Response {
    /**
     * Constructs a new <code>GetServerStatus200Response</code>.
     * @alias module:model/GetServerStatus200Response
     * @param runsEnabled {Boolean} Whether users can run scripts and pipelines. False when BLOCK_RUNS=true in runner.env, which makes this a results-only server where existing results can be viewed but nothing new can be run.
     * @param savePipelineToServer {Boolean} Whether pipelines can be saved directly to the server from the editor. False when SAVE_PIPELINE_TO_SERVER=deny in runner.env; users must then copy the pipeline to the clipboard and submit it through git.
     * @param condaPackEnabled {Boolean} Whether conda environments are packed with conda-pack and cached, so they can be reused instead of rebuilt. Controlled by CONDA_PACK_ENABLED in runner.env (true to turn it on). Read once at server start.
     * @param myFilesEnabled {Boolean} Whether users can upload and manage their own files in the file manager. False when DISABLE_MY_FILES=true in runner.env, which makes the file manager read-only.
     * @param chatEnabled {Boolean} Whether the AI assistant is shown in the UI. False when DISABLE_CHAT=true in runner.env. The MCP server keeps running either way, so this flag does not tell whether MCP is available.
     */
    constructor(runsEnabled, savePipelineToServer, condaPackEnabled, myFilesEnabled, chatEnabled) { 
        
        GetServerStatus200Response.initialize(this, runsEnabled, savePipelineToServer, condaPackEnabled, myFilesEnabled, chatEnabled);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, runsEnabled, savePipelineToServer, condaPackEnabled, myFilesEnabled, chatEnabled) { 
        obj['runsEnabled'] = runsEnabled;
        obj['savePipelineToServer'] = savePipelineToServer;
        obj['condaPackEnabled'] = condaPackEnabled;
        obj['myFilesEnabled'] = myFilesEnabled;
        obj['chatEnabled'] = chatEnabled;
    }

    /**
     * Constructs a <code>GetServerStatus200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetServerStatus200Response} obj Optional instance to populate.
     * @return {module:model/GetServerStatus200Response} The populated <code>GetServerStatus200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetServerStatus200Response();

            if (data.hasOwnProperty('runsEnabled')) {
                obj['runsEnabled'] = ApiClient.convertToType(data['runsEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('savePipelineToServer')) {
                obj['savePipelineToServer'] = ApiClient.convertToType(data['savePipelineToServer'], 'Boolean');
            }
            if (data.hasOwnProperty('condaPackEnabled')) {
                obj['condaPackEnabled'] = ApiClient.convertToType(data['condaPackEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('myFilesEnabled')) {
                obj['myFilesEnabled'] = ApiClient.convertToType(data['myFilesEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('chatEnabled')) {
                obj['chatEnabled'] = ApiClient.convertToType(data['chatEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetServerStatus200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetServerStatus200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetServerStatus200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

GetServerStatus200Response.RequiredProperties = ["runsEnabled", "savePipelineToServer", "condaPackEnabled", "myFilesEnabled", "chatEnabled"];

/**
 * Whether users can run scripts and pipelines. False when BLOCK_RUNS=true in runner.env, which makes this a results-only server where existing results can be viewed but nothing new can be run.
 * @member {Boolean} runsEnabled
 */
GetServerStatus200Response.prototype['runsEnabled'] = undefined;

/**
 * Whether pipelines can be saved directly to the server from the editor. False when SAVE_PIPELINE_TO_SERVER=deny in runner.env; users must then copy the pipeline to the clipboard and submit it through git.
 * @member {Boolean} savePipelineToServer
 */
GetServerStatus200Response.prototype['savePipelineToServer'] = undefined;

/**
 * Whether conda environments are packed with conda-pack and cached, so they can be reused instead of rebuilt. Controlled by CONDA_PACK_ENABLED in runner.env (true to turn it on). Read once at server start.
 * @member {Boolean} condaPackEnabled
 */
GetServerStatus200Response.prototype['condaPackEnabled'] = undefined;

/**
 * Whether users can upload and manage their own files in the file manager. False when DISABLE_MY_FILES=true in runner.env, which makes the file manager read-only.
 * @member {Boolean} myFilesEnabled
 */
GetServerStatus200Response.prototype['myFilesEnabled'] = undefined;

/**
 * Whether the AI assistant is shown in the UI. False when DISABLE_CHAT=true in runner.env. The MCP server keeps running either way, so this flag does not tell whether MCP is available.
 * @member {Boolean} chatEnabled
 */
GetServerStatus200Response.prototype['chatEnabled'] = undefined;






export default GetServerStatus200Response;

