/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetServerStatus200Response model module.
 * @module model/GetServerStatus200Response
 * @version 2.3.0
 */
class GetServerStatus200Response {
    /**
     * Constructs a new <code>GetServerStatus200Response</code>.
     * @alias module:model/GetServerStatus200Response
     * @param runsEnabled {Boolean} False when BLOCK_RUNS makes this a results-only server.
     * @param savePipelineToServer {Boolean} False when SAVE_PIPELINE_TO_SERVER denies the save API.
     * @param condaPackEnabled {Boolean} Whether conda environments are cached with conda-pack.
     * @param myFilesEnabled {Boolean} False when DISABLE_MY_FILES makes the file manager read-only.
     * @param antivirusEnabled {Boolean} Whether uploads are scanned. When false they are saved unscanned; when true an unscannable upload is refused rather than saved. 
     */
    constructor(runsEnabled, savePipelineToServer, condaPackEnabled, myFilesEnabled, antivirusEnabled) { 
        
        GetServerStatus200Response.initialize(this, runsEnabled, savePipelineToServer, condaPackEnabled, myFilesEnabled, antivirusEnabled);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, runsEnabled, savePipelineToServer, condaPackEnabled, myFilesEnabled, antivirusEnabled) { 
        obj['runsEnabled'] = runsEnabled;
        obj['savePipelineToServer'] = savePipelineToServer;
        obj['condaPackEnabled'] = condaPackEnabled;
        obj['myFilesEnabled'] = myFilesEnabled;
        obj['antivirusEnabled'] = antivirusEnabled;
    }

    /**
     * Constructs a <code>GetServerStatus200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetServerStatus200Response} obj Optional instance to populate.
     * @return {module:model/GetServerStatus200Response} The populated <code>GetServerStatus200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetServerStatus200Response();

            if (data.hasOwnProperty('runsEnabled')) {
                obj['runsEnabled'] = ApiClient.convertToType(data['runsEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('savePipelineToServer')) {
                obj['savePipelineToServer'] = ApiClient.convertToType(data['savePipelineToServer'], 'Boolean');
            }
            if (data.hasOwnProperty('condaPackEnabled')) {
                obj['condaPackEnabled'] = ApiClient.convertToType(data['condaPackEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('myFilesEnabled')) {
                obj['myFilesEnabled'] = ApiClient.convertToType(data['myFilesEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('antivirusEnabled')) {
                obj['antivirusEnabled'] = ApiClient.convertToType(data['antivirusEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('antivirusReachable')) {
                obj['antivirusReachable'] = ApiClient.convertToType(data['antivirusReachable'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetServerStatus200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetServerStatus200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetServerStatus200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

GetServerStatus200Response.RequiredProperties = ["runsEnabled", "savePipelineToServer", "condaPackEnabled", "myFilesEnabled", "antivirusEnabled"];

/**
 * False when BLOCK_RUNS makes this a results-only server.
 * @member {Boolean} runsEnabled
 */
GetServerStatus200Response.prototype['runsEnabled'] = undefined;

/**
 * False when SAVE_PIPELINE_TO_SERVER denies the save API.
 * @member {Boolean} savePipelineToServer
 */
GetServerStatus200Response.prototype['savePipelineToServer'] = undefined;

/**
 * Whether conda environments are cached with conda-pack.
 * @member {Boolean} condaPackEnabled
 */
GetServerStatus200Response.prototype['condaPackEnabled'] = undefined;

/**
 * False when DISABLE_MY_FILES makes the file manager read-only.
 * @member {Boolean} myFilesEnabled
 */
GetServerStatus200Response.prototype['myFilesEnabled'] = undefined;

/**
 * Whether uploads are scanned. When false they are saved unscanned; when true an unscannable upload is refused rather than saved. 
 * @member {Boolean} antivirusEnabled
 */
GetServerStatus200Response.prototype['antivirusEnabled'] = undefined;

/**
 * Whether the scanner currently answers, or null when antivirus is off. False here means uploads are being refused, because the scan path fails closed. 
 * @member {Boolean} antivirusReachable
 */
GetServerStatus200Response.prototype['antivirusReachable'] = undefined;






export default GetServerStatus200Response;

