/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoOutputsValueTypeOneOf model module.
 * @module model/InfoOutputsValueTypeOneOf
 * @version 1.0.0
 */
class InfoOutputsValueTypeOneOf {
    /**
     * Constructs a new <code>InfoOutputsValueTypeOneOf</code>.
     * @alias module:model/InfoOutputsValueTypeOneOf
     */
    constructor() { 
        
        InfoOutputsValueTypeOneOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InfoOutputsValueTypeOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoOutputsValueTypeOneOf} obj Optional instance to populate.
     * @return {module:model/InfoOutputsValueTypeOneOf} The populated <code>InfoOutputsValueTypeOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoOutputsValueTypeOneOf();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InfoOutputsValueTypeOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InfoOutputsValueTypeOneOf</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['from'] && !(typeof data['from'] === 'string' || data['from'] instanceof String)) {
            throw new Error("Expected the field `from` to be a primitive type in the JSON string but got " + data['from']);
        }

        return true;
    }


}



/**
 * @member {String} from
 */
InfoOutputsValueTypeOneOf.prototype['from'] = undefined;






export default InfoOutputsValueTypeOneOf;

