/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoHpc model module.
 * @module model/InfoHpc
 * @version 1.0.0
 */
class InfoHpc {
    /**
     * Constructs a new <code>InfoHpc</code>.
     * @alias module:model/InfoHpc
     */
    constructor() { 
        
        InfoHpc.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InfoHpc</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoHpc} obj Optional instance to populate.
     * @return {module:model/InfoHpc} The populated <code>InfoHpc</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoHpc();

            if (data.hasOwnProperty('mem')) {
                obj['mem'] = ApiClient.convertToType(data['mem'], 'String');
            }
            if (data.hasOwnProperty('cpus-per-task')) {
                obj['cpus-per-task'] = ApiClient.convertToType(data['cpus-per-task'], 'Number');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InfoHpc</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InfoHpc</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mem'] && !(typeof data['mem'] === 'string' || data['mem'] instanceof String)) {
            throw new Error("Expected the field `mem` to be a primitive type in the JSON string but got " + data['mem']);
        }
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }

        return true;
    }


}



/**
 * Maximum amount of memory allowed before Out Of Memory exception occurs.
 * @member {String} mem
 */
InfoHpc.prototype['mem'] = undefined;

/**
 * Number of CPUs for this task.
 * @member {Number} cpus-per-task
 */
InfoHpc.prototype['cpus-per-task'] = undefined;

/**
 * Maximum time allowed before timeout, for syntax see https://slurm.schedmd.com/sbatch.html#OPT_time.
 * @member {String} time
 */
InfoHpc.prototype['time'] = undefined;






export default InfoHpc;

