/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InfoLifecycleOneOf from './InfoLifecycleOneOf';
import InfoLifecycleOneOf1 from './InfoLifecycleOneOf1';

/**
 * The InfoLifecycle model module.
 * @module model/InfoLifecycle
 * @version 1.0.0
 */
class InfoLifecycle {
    /**
     * Constructs a new <code>InfoLifecycle</code>.
     * @alias module:model/InfoLifecycle
     * @param {(module:model/InfoLifecycleOneOf|module:model/InfoLifecycleOneOf1)} instance The actual instance to initialize InfoLifecycle.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "InfoLifecycleOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                InfoLifecycleOneOf.validateJSON(instance); // throw an exception if no match
                // create InfoLifecycleOneOf from JS object
                this.actualInstance = InfoLifecycleOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into InfoLifecycleOneOf
            errorMessages.push("Failed to construct InfoLifecycleOneOf: " + err)
        }

        try {
            if (typeof instance === "InfoLifecycleOneOf1") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                InfoLifecycleOneOf1.validateJSON(instance); // throw an exception if no match
                // create InfoLifecycleOneOf1 from JS object
                this.actualInstance = InfoLifecycleOneOf1.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into InfoLifecycleOneOf1
            errorMessages.push("Failed to construct InfoLifecycleOneOf1: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `InfoLifecycle` with oneOf schemas InfoLifecycleOneOf, InfoLifecycleOneOf1. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `InfoLifecycle` with oneOf schemas InfoLifecycleOneOf, InfoLifecycleOneOf1. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>InfoLifecycle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoLifecycle} obj Optional instance to populate.
     * @return {module:model/InfoLifecycle} The populated <code>InfoLifecycle</code> instance.
     */
    static constructFromObject(data, obj) {
        return new InfoLifecycle(data);
    }

    /**
     * Gets the actual instance, which can be <code>InfoLifecycleOneOf</code>, <code>InfoLifecycleOneOf1</code>.
     * @return {(module:model/InfoLifecycleOneOf|module:model/InfoLifecycleOneOf1)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>InfoLifecycleOneOf</code>, <code>InfoLifecycleOneOf1</code>.
     * @param {(module:model/InfoLifecycleOneOf|module:model/InfoLifecycleOneOf1)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = InfoLifecycle.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of InfoLifecycle from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/InfoLifecycle} An instance of InfoLifecycle.
     */
    static fromJSON = function(json_string){
        return InfoLifecycle.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/InfoLifecycle.StatusEnum} status
 */
InfoLifecycle.prototype['status'] = undefined;

/**
 * @member {String} message
 */
InfoLifecycle.prototype['message'] = undefined;


InfoLifecycle.OneOf = ["InfoLifecycleOneOf", "InfoLifecycleOneOf1"];

export default InfoLifecycle;

