/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoLifecycleOneOf model module.
 * @module model/InfoLifecycleOneOf
 * @version 1.0.0
 */
class InfoLifecycleOneOf {
    /**
     * Constructs a new <code>InfoLifecycleOneOf</code>.
     * @alias module:model/InfoLifecycleOneOf
     * @param status {module:model/InfoLifecycleOneOf.StatusEnum} 
     */
    constructor(status) { 
        
        InfoLifecycleOneOf.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status || 'in_development';
    }

    /**
     * Constructs a <code>InfoLifecycleOneOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoLifecycleOneOf} obj Optional instance to populate.
     * @return {module:model/InfoLifecycleOneOf} The populated <code>InfoLifecycleOneOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoLifecycleOneOf();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InfoLifecycleOneOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InfoLifecycleOneOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InfoLifecycleOneOf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

InfoLifecycleOneOf.RequiredProperties = ["status"];

/**
 * @member {module:model/InfoLifecycleOneOf.StatusEnum} status
 * @default 'in_development'
 */
InfoLifecycleOneOf.prototype['status'] = 'in_development';

/**
 * @member {String} message
 */
InfoLifecycleOneOf.prototype['message'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
InfoLifecycleOneOf['StatusEnum'] = {

    /**
     * value: "in_development"
     * @const
     */
    "in_development": "in_development",

    /**
     * value: "in_review"
     * @const
     */
    "in_review": "in_review",

    /**
     * value: "reviewed"
     * @const
     */
    "reviewed": "reviewed"
};



export default InfoLifecycleOneOf;

