/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoCompute model module.
 * @module model/InfoCompute
 * @version 1.0.0
 */
class InfoCompute {
    /**
     * Constructs a new <code>InfoCompute</code>.
     * @alias module:model/InfoCompute
     */
    constructor() { 
        
        InfoCompute.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InfoCompute</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoCompute} obj Optional instance to populate.
     * @return {module:model/InfoCompute} The populated <code>InfoCompute</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoCompute();

            if (data.hasOwnProperty('hpc')) {
                obj['hpc'] = ApiClient.convertToType(data['hpc'], 'Boolean');
            }
            if (data.hasOwnProperty('mem')) {
                obj['mem'] = ApiClient.convertToType(data['mem'], 'String');
            }
            if (data.hasOwnProperty('cpus-per-task')) {
                obj['cpus-per-task'] = ApiClient.convertToType(data['cpus-per-task'], 'Number');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InfoCompute</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InfoCompute</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mem'] && !(typeof data['mem'] === 'string' || data['mem'] instanceof String)) {
            throw new Error("Expected the field `mem` to be a primitive type in the JSON string but got " + data['mem']);
        }
        // ensure the json data is a string
        if (data['time'] && !(typeof data['time'] === 'string' || data['time'] instanceof String)) {
            throw new Error("Expected the field `time` to be a primitive type in the JSON string but got " + data['time']);
        }

        return true;
    }


}



/**
 * Whether this script is meant to be run on a HPC. If true, the script will be run on a HPC when configured, otherwise on kubernetes or locally. 
 * @member {Boolean} hpc
 */
InfoCompute.prototype['hpc'] = undefined;

/**
 * Maximum amount of memory allowed before Out Of Memory exception occurs.
 * @member {String} mem
 */
InfoCompute.prototype['mem'] = undefined;

/**
 * Number of CPUs for this task.
 * @member {Number} cpus-per-task
 */
InfoCompute.prototype['cpus-per-task'] = undefined;

/**
 * Maximum time allowed before timeout, for syntax see https://slurm.schedmd.com/sbatch.html#OPT_time.
 * @member {String} time
 */
InfoCompute.prototype['time'] = undefined;






export default InfoCompute;

