/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoLifecycleOneOf1 model module.
 * @module model/InfoLifecycleOneOf1
 * @version 1.0.0
 */
class InfoLifecycleOneOf1 {
    /**
     * Constructs a new <code>InfoLifecycleOneOf1</code>.
     * @alias module:model/InfoLifecycleOneOf1
     * @param status {module:model/InfoLifecycleOneOf1.StatusEnum} 
     * @param message {String} 
     */
    constructor(status, message) { 
        
        InfoLifecycleOneOf1.initialize(this, status, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, message) { 
        obj['status'] = status;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>InfoLifecycleOneOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoLifecycleOneOf1} obj Optional instance to populate.
     * @return {module:model/InfoLifecycleOneOf1} The populated <code>InfoLifecycleOneOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoLifecycleOneOf1();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InfoLifecycleOneOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InfoLifecycleOneOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InfoLifecycleOneOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

InfoLifecycleOneOf1.RequiredProperties = ["status", "message"];

/**
 * @member {module:model/InfoLifecycleOneOf1.StatusEnum} status
 */
InfoLifecycleOneOf1.prototype['status'] = undefined;

/**
 * @member {String} message
 */
InfoLifecycleOneOf1.prototype['message'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
InfoLifecycleOneOf1['StatusEnum'] = {

    /**
     * value: "deprecated"
     * @const
     */
    "deprecated": "deprecated"
};



export default InfoLifecycleOneOf1;

