/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoLifecycle model module.
 * @module model/InfoLifecycle
 * @version 1.0.0
 */
class InfoLifecycle {
    /**
     * Constructs a new <code>InfoLifecycle</code>.
     * @alias module:model/InfoLifecycle
     */
    constructor() { 
        
        InfoLifecycle.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['status'] = 'in_development';
    }

    /**
     * Constructs a <code>InfoLifecycle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoLifecycle} obj Optional instance to populate.
     * @return {module:model/InfoLifecycle} The populated <code>InfoLifecycle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoLifecycle();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InfoLifecycle</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InfoLifecycle</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {module:model/InfoLifecycle.StatusEnum} status
 * @default 'in_development'
 */
InfoLifecycle.prototype['status'] = 'in_development';

/**
 * @member {String} message
 */
InfoLifecycle.prototype['message'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
InfoLifecycle['StatusEnum'] = {

    /**
     * value: "in_development"
     * @const
     */
    "in_development": "in_development",

    /**
     * value: "in_review"
     * @const
     */
    "in_review": "in_review",

    /**
     * value: "reviewed"
     * @const
     */
    "reviewed": "reviewed",

    /**
     * value: "deprecated"
     * @const
     */
    "deprecated": "deprecated"
};



export default InfoLifecycle;

