/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IsFileManagerDisabled200Response model module.
 * @module model/IsFileManagerDisabled200Response
 * @version 1.0.0
 */
class IsFileManagerDisabled200Response {
    /**
     * Constructs a new <code>IsFileManagerDisabled200Response</code>.
     * @alias module:model/IsFileManagerDisabled200Response
     */
    constructor() { 
        
        IsFileManagerDisabled200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IsFileManagerDisabled200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IsFileManagerDisabled200Response} obj Optional instance to populate.
     * @return {module:model/IsFileManagerDisabled200Response} The populated <code>IsFileManagerDisabled200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IsFileManagerDisabled200Response();

            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IsFileManagerDisabled200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IsFileManagerDisabled200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} disabled
 */
IsFileManagerDisabled200Response.prototype['disabled'] = undefined;






export default IsFileManagerDisabled200Response;

