/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MoveCopyItemRequest model module.
 * @module model/MoveCopyItemRequest
 * @version 1.0.0
 */
class MoveCopyItemRequest {
    /**
     * Constructs a new <code>MoveCopyItemRequest</code>.
     * @alias module:model/MoveCopyItemRequest
     * @param operation {module:model/MoveCopyItemRequest.OperationEnum} The action to perform. Must be set to 'move' or 'copy'.
     * @param target {String} The ID for the destination folder in where the files/folders will move into.
     * @param ids {Array.<String>} An array containing the IDs of the files/folders that will be processed.
     */
    constructor(operation, target, ids) { 
        
        MoveCopyItemRequest.initialize(this, operation, target, ids);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operation, target, ids) { 
        obj['operation'] = operation;
        obj['target'] = target;
        obj['ids'] = ids;
    }

    /**
     * Constructs a <code>MoveCopyItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MoveCopyItemRequest} obj Optional instance to populate.
     * @return {module:model/MoveCopyItemRequest} The populated <code>MoveCopyItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MoveCopyItemRequest();

            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MoveCopyItemRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MoveCopyItemRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MoveCopyItemRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['operation'] && !(typeof data['operation'] === 'string' || data['operation'] instanceof String)) {
            throw new Error("Expected the field `operation` to be a primitive type in the JSON string but got " + data['operation']);
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ids'])) {
            throw new Error("Expected the field `ids` to be an array in the JSON data but got " + data['ids']);
        }

        return true;
    }


}

MoveCopyItemRequest.RequiredProperties = ["operation", "target", "ids"];

/**
 * The action to perform. Must be set to 'move' or 'copy'.
 * @member {module:model/MoveCopyItemRequest.OperationEnum} operation
 */
MoveCopyItemRequest.prototype['operation'] = undefined;

/**
 * The ID for the destination folder in where the files/folders will move into.
 * @member {String} target
 */
MoveCopyItemRequest.prototype['target'] = undefined;

/**
 * An array containing the IDs of the files/folders that will be processed.
 * @member {Array.<String>} ids
 */
MoveCopyItemRequest.prototype['ids'] = undefined;





/**
 * Allowed values for the <code>operation</code> property.
 * @enum {String}
 * @readonly
 */
MoveCopyItemRequest['OperationEnum'] = {

    /**
     * value: "move"
     * @const
     */
    "move": "move",

    /**
     * value: "copy"
     * @const
     */
    "copy": "copy"
};



export default MoveCopyItemRequest;

