/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MoveCopyItem200ResponseResultInner from './MoveCopyItem200ResponseResultInner';

/**
 * The MoveCopyItem200Response model module.
 * @module model/MoveCopyItem200Response
 * @version 1.0.0
 */
class MoveCopyItem200Response {
    /**
     * Constructs a new <code>MoveCopyItem200Response</code>.
     * @alias module:model/MoveCopyItem200Response
     */
    constructor() { 
        
        MoveCopyItem200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MoveCopyItem200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MoveCopyItem200Response} obj Optional instance to populate.
     * @return {module:model/MoveCopyItem200Response} The populated <code>MoveCopyItem200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MoveCopyItem200Response();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], [MoveCopyItem200ResponseResultInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MoveCopyItem200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MoveCopyItem200Response</code>.
     */
    static validateJSON(data) {
        if (data['result']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['result'])) {
                throw new Error("Expected the field `result` to be an array in the JSON data but got " + data['result']);
            }
            // validate the optional field `result` (array)
            for (const item of data['result']) {
                MoveCopyItem200ResponseResultInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/MoveCopyItem200ResponseResultInner>} result
 */
MoveCopyItem200Response.prototype['result'] = undefined;






export default MoveCopyItem200Response;

