/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RenameItemRequest model module.
 * @module model/RenameItemRequest
 * @version 1.0.0
 */
class RenameItemRequest {
    /**
     * Constructs a new <code>RenameItemRequest</code>.
     * @alias module:model/RenameItemRequest
     * @param operation {module:model/RenameItemRequest.OperationEnum} The action to perform. Must be set to 'rename'.
     * @param name {String} The new name for the file or folder (including its extension).
     */
    constructor(operation, name) { 
        
        RenameItemRequest.initialize(this, operation, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operation, name) { 
        obj['operation'] = operation;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>RenameItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RenameItemRequest} obj Optional instance to populate.
     * @return {module:model/RenameItemRequest} The populated <code>RenameItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RenameItemRequest();

            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RenameItemRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RenameItemRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RenameItemRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['operation'] && !(typeof data['operation'] === 'string' || data['operation'] instanceof String)) {
            throw new Error("Expected the field `operation` to be a primitive type in the JSON string but got " + data['operation']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

RenameItemRequest.RequiredProperties = ["operation", "name"];

/**
 * The action to perform. Must be set to 'rename'.
 * @member {module:model/RenameItemRequest.OperationEnum} operation
 */
RenameItemRequest.prototype['operation'] = undefined;

/**
 * The new name for the file or folder (including its extension).
 * @member {String} name
 */
RenameItemRequest.prototype['name'] = undefined;





/**
 * Allowed values for the <code>operation</code> property.
 * @enum {String}
 * @readonly
 */
RenameItemRequest['OperationEnum'] = {

    /**
     * value: "rename"
     * @const
     */
    "rename": "rename"
};



export default RenameItemRequest;

