/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RenameItem200ResponseResult from './RenameItem200ResponseResult';

/**
 * The RenameItem200Response model module.
 * @module model/RenameItem200Response
 * @version 1.0.0
 */
class RenameItem200Response {
    /**
     * Constructs a new <code>RenameItem200Response</code>.
     * @alias module:model/RenameItem200Response
     */
    constructor() { 
        
        RenameItem200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RenameItem200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RenameItem200Response} obj Optional instance to populate.
     * @return {module:model/RenameItem200Response} The populated <code>RenameItem200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RenameItem200Response();

            if (data.hasOwnProperty('result')) {
                obj['result'] = RenameItem200ResponseResult.constructFromObject(data['result']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RenameItem200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RenameItem200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          RenameItem200ResponseResult.validateJSON(data['result']);
        }

        return true;
    }


}



/**
 * @member {module:model/RenameItem200ResponseResult} result
 */
RenameItem200Response.prototype['result'] = undefined;






export default RenameItem200Response;

