---
- name: Install Bon-in-a-box test server
  hosts: biabserver
  become: true

  tasks:
    - name: "Run updates"
      ansible.builtin.apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Create data mount point
      file:
        path: /home/ubuntu/data
        state: directory

    - name: Mount and bind data drive
      ansible.posix.mount:
        path: /home/ubuntu/data
        src: /dev/vdb
        opts: defaults,nofail
        state: mounted
        fstype: xfs

    - name: Change ownership of data drive
      ansible.builtin.file:
        path: /home/ubuntu/data
        owner: ubuntu
        group: ubuntu

    - name: CERTBOT.
      include_role:
        name: geerlingguy.certbot
      vars:
        certbot_admin_email: web@geobon.org
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: []
        certbot_certs:
          - domains:
              - biab2.geobon.org

    - name: NGINX - server
      include_role:
        name: geerlingguy.nginx
      vars:
        nginx_vhosts:
          - listen: "443 ssl http2"
            server_name: "biab2.geobon.org"
            index: "index.html index.htm"
            state: "present"
            filename: "biab-main.conf"
            extra_parameters: |
              location / {
                  proxy_pass http://localhost:80;
                  proxy_read_timeout 100000;
                  proxy_connect_timeout 100000;
                  proxy_send_timeout 100000;
                  add_header Access-Control-Allow-Origin *;
                  
                  # WebSocket support
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection $connection_upgrade;
              }
              ssl_certificate     /etc/letsencrypt/live/biab2.geobon.org/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/biab2.geobon.org/privkey.pem;
              ssl_protocols       TLSv1.1 TLSv1.2;
              ssl_ciphers         HIGH:!aNULL:!MD5;

    - name: NGINX - biab conf file
      copy:
        dest: "/etc/nginx/conf.d/biab.conf"
        content: |
          # WebSocket support
          map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
          }

    - name: NGINX - remove default conf file
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: DOCKER.
      include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_install_compose_plugin: true
        docker_users:
          - ubuntu
        docker_daemon_options:
          data-root: "/home/ubuntu/data/docker/"

    - name: Pull BON in a Box from Git
      become_user: ubuntu
      ansible.builtin.git:
        repo: https://github.com/GEO-BON/bon-in-a-box-pipelines
        dest: /home/ubuntu/data/biab-2.0/
        force: true
        
    - name: docker compose pull
      become_user: ubuntu
      ansible.builtin.shell: docker compose -f compose.yml -f compose.override.yml pull
      args:
        chdir: /home/ubuntu/data/biab-2.0/

    - name: docker compose up
      become_user: ubuntu
      ansible.builtin.shell: docker compose -f compose.yml -f compose.override.yml up -d
      args:
        chdir: /home/ubuntu/data/biab-2.0/
