/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateItem200Response from './model/CreateItem200Response';
import CreateItem200ResponseResult from './model/CreateItem200ResponseResult';
import CreateItemRequest from './model/CreateItemRequest';
import DeleteItem200Response from './model/DeleteItem200Response';
import DeleteItemRequest from './model/DeleteItemRequest';
import GetFileStorage200Response from './model/GetFileStorage200Response';
import GetFileStorage200ResponseStats from './model/GetFileStorage200ResponseStats';
import GetHPCStatus200ResponseValue from './model/GetHPCStatus200ResponseValue';
import GetHistory200ResponseInner from './model/GetHistory200ResponseInner';
import GetRootItems200ResponseInner from './model/GetRootItems200ResponseInner';
import GetRootItems403Response from './model/GetRootItems403Response';
import Info from './model/Info';
import InfoAuthorInner from './model/InfoAuthorInner';
import InfoCompute from './model/InfoCompute';
import InfoInputsValue from './model/InfoInputsValue';
import InfoInputsValueExample from './model/InfoInputsValueExample';
import InfoInputsValueExampleOneOfInner from './model/InfoInputsValueExampleOneOfInner';
import InfoLifecycle from './model/InfoLifecycle';
import InfoOutputsValue from './model/InfoOutputsValue';
import InfoOutputsValueExample from './model/InfoOutputsValueExample';
import InfoReferencesInner from './model/InfoReferencesInner';
import InfoReviewerInner from './model/InfoReviewerInner';
import IsFileManagerDisabled200Response from './model/IsFileManagerDisabled200Response';
import MoveCopyItem200Response from './model/MoveCopyItem200Response';
import MoveCopyItem200ResponseResultInner from './model/MoveCopyItem200ResponseResultInner';
import MoveCopyItemRequest from './model/MoveCopyItemRequest';
import RenameItem200Response from './model/RenameItem200Response';
import RenameItem200ResponseResult from './model/RenameItem200ResponseResult';
import RenameItemRequest from './model/RenameItemRequest';
import UploadFile200Response from './model/UploadFile200Response';
import DefaultApi from './api/DefaultApi';
import FileManagerApi from './api/FileManagerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BonInABoxScriptService = require('index'); // See note below*.
* var xxxSvc = new BonInABoxScriptService.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BonInABoxScriptService.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BonInABoxScriptService.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BonInABoxScriptService.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateItem200Response model constructor.
     * @property {module:model/CreateItem200Response}
     */
    CreateItem200Response,

    /**
     * The CreateItem200ResponseResult model constructor.
     * @property {module:model/CreateItem200ResponseResult}
     */
    CreateItem200ResponseResult,

    /**
     * The CreateItemRequest model constructor.
     * @property {module:model/CreateItemRequest}
     */
    CreateItemRequest,

    /**
     * The DeleteItem200Response model constructor.
     * @property {module:model/DeleteItem200Response}
     */
    DeleteItem200Response,

    /**
     * The DeleteItemRequest model constructor.
     * @property {module:model/DeleteItemRequest}
     */
    DeleteItemRequest,

    /**
     * The GetFileStorage200Response model constructor.
     * @property {module:model/GetFileStorage200Response}
     */
    GetFileStorage200Response,

    /**
     * The GetFileStorage200ResponseStats model constructor.
     * @property {module:model/GetFileStorage200ResponseStats}
     */
    GetFileStorage200ResponseStats,

    /**
     * The GetHPCStatus200ResponseValue model constructor.
     * @property {module:model/GetHPCStatus200ResponseValue}
     */
    GetHPCStatus200ResponseValue,

    /**
     * The GetHistory200ResponseInner model constructor.
     * @property {module:model/GetHistory200ResponseInner}
     */
    GetHistory200ResponseInner,

    /**
     * The GetRootItems200ResponseInner model constructor.
     * @property {module:model/GetRootItems200ResponseInner}
     */
    GetRootItems200ResponseInner,

    /**
     * The GetRootItems403Response model constructor.
     * @property {module:model/GetRootItems403Response}
     */
    GetRootItems403Response,

    /**
     * The Info model constructor.
     * @property {module:model/Info}
     */
    Info,

    /**
     * The InfoAuthorInner model constructor.
     * @property {module:model/InfoAuthorInner}
     */
    InfoAuthorInner,

    /**
     * The InfoCompute model constructor.
     * @property {module:model/InfoCompute}
     */
    InfoCompute,

    /**
     * The InfoInputsValue model constructor.
     * @property {module:model/InfoInputsValue}
     */
    InfoInputsValue,

    /**
     * The InfoInputsValueExample model constructor.
     * @property {module:model/InfoInputsValueExample}
     */
    InfoInputsValueExample,

    /**
     * The InfoInputsValueExampleOneOfInner model constructor.
     * @property {module:model/InfoInputsValueExampleOneOfInner}
     */
    InfoInputsValueExampleOneOfInner,

    /**
     * The InfoLifecycle model constructor.
     * @property {module:model/InfoLifecycle}
     */
    InfoLifecycle,

    /**
     * The InfoOutputsValue model constructor.
     * @property {module:model/InfoOutputsValue}
     */
    InfoOutputsValue,

    /**
     * The InfoOutputsValueExample model constructor.
     * @property {module:model/InfoOutputsValueExample}
     */
    InfoOutputsValueExample,

    /**
     * The InfoReferencesInner model constructor.
     * @property {module:model/InfoReferencesInner}
     */
    InfoReferencesInner,

    /**
     * The InfoReviewerInner model constructor.
     * @property {module:model/InfoReviewerInner}
     */
    InfoReviewerInner,

    /**
     * The IsFileManagerDisabled200Response model constructor.
     * @property {module:model/IsFileManagerDisabled200Response}
     */
    IsFileManagerDisabled200Response,

    /**
     * The MoveCopyItem200Response model constructor.
     * @property {module:model/MoveCopyItem200Response}
     */
    MoveCopyItem200Response,

    /**
     * The MoveCopyItem200ResponseResultInner model constructor.
     * @property {module:model/MoveCopyItem200ResponseResultInner}
     */
    MoveCopyItem200ResponseResultInner,

    /**
     * The MoveCopyItemRequest model constructor.
     * @property {module:model/MoveCopyItemRequest}
     */
    MoveCopyItemRequest,

    /**
     * The RenameItem200Response model constructor.
     * @property {module:model/RenameItem200Response}
     */
    RenameItem200Response,

    /**
     * The RenameItem200ResponseResult model constructor.
     * @property {module:model/RenameItem200ResponseResult}
     */
    RenameItem200ResponseResult,

    /**
     * The RenameItemRequest model constructor.
     * @property {module:model/RenameItemRequest}
     */
    RenameItemRequest,

    /**
     * The UploadFile200Response model constructor.
     * @property {module:model/UploadFile200Response}
     */
    UploadFile200Response,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The FileManagerApi service constructor.
    * @property {module:api/FileManagerApi}
    */
    FileManagerApi
};
