project:
  type: website
  output-dir: docs

website:
  title: "BON in a Box"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - documentation/about.qmd
      - documentation/how_to_install.qmd
      - documentation/how_to_contribute.qmd
      - documentation/working_with_stac.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

