---
title: "About"
---

## What is BON in a Box?

BON in a Box serves as a hub for Biodiversity Observation Networks (BONs), consolidating diverse tools and resources to enhance data analysis and collaboration. It's the ultimate ecosystem for harmonizing biodiversity observations, fostering efficiency, and amplifying the power of data-driven insights.

BON in a Box now features a community-contributed and open-source data to essential biodiversity variable (EBV) and indicator workflow repository curated by GEO BON. Its engine allows to seamlessly connect steps in different languages (R, Julia, Python) through a modular pipeline approach that reads both from local and global data sources. These pipelines can calculate EBVs and indicators using publicaly available data or user-provided data.

## Why do we need this platform?

Scientists around the world are developing tools to create workflows to calculate essential biodiversity variables and indicators to report on biodiversity change. However, there are almost no platforms to share these workflows and tools, leading to duplication of effort. BON in a Box is a platform to consolidate these tools and facilitate coordination and networking between scientists, organizations, and governments to face the global biodiversity crisis.

## Why should you contribute? 

Contributing to BON in a Box will increase the impact of your research by allowing your analysis workflows to be used in broader areas and contexts for decision-making. Contributors will become part of a global community to generate analyses of the state and trends of biodiversity to inform management decisions.

## 
