name: On push, any branch

on:
  push:
    paths:
      - "script-server/**"
      - "script-stubs/**"
      - ".github/workflows/onPush.yml"
      - ".github/scriptValidationSchema.yml"
      - ".github/pipelineValidationSchema.yml"
      - ".github/validateCerberusSchema.py"
      - ".github/findDuplicateDescriptions.sh"
      - ".github/findDuplicateIds.sh"

jobs:
  run-script-server-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2

    - name: Gradle build & test
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build --info
        build-root-directory: script-server

    - name: Save test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test results
        path: script-server/build/reports/tests/test/

  run-script-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: YML syntax validation (test files)
      uses: navikt/yaml-validator@v4
      with:
        schema_path: .github/scriptValidationSchema.yml
        document_path: script-server/src/test/resources/scripts/
        validate_file_extension: no
        filter_extensions: .yml
    - name: YML test files syntax validation (stubs)
      uses: navikt/yaml-validator@v4
      with:
        schema_path: .github/scriptValidationSchema.yml
        document_path: script-stubs
        validate_file_extension: no
        filter_extensions: .yml
    - name: Find duplicate lines inside step YML file (test files)
      working-directory: script-server/src/test/resources/scripts/
      run:  $GITHUB_WORKSPACE/.github/findDuplicateDescriptions.sh
      shell: bash
    - name: Find duplicate lines inside step YML file (stubs)
      working-directory: script-stubs
      run:  $GITHUB_WORKSPACE/.github/findDuplicateDescriptions.sh
      shell: bash

  run-pipeline-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install cerberus
    - name: Metadata validation
      working-directory: script-server/src/test/resources/pipelines/
      run: python3 $GITHUB_WORKSPACE/.github/validateCerberusSchema.py $GITHUB_WORKSPACE/.github/pipelineValidationSchema.yml
    - name: Find duplicate lines inside same pipeline JSON file
      working-directory: script-server/src/test/resources/pipelines/
      run:  $GITHUB_WORKSPACE/.github/findDuplicateIds.sh
      shell: bash